apiVersion: v1
kind: Service
metadata:
  name: {{ include "keyway.fullname" . }}
  labels:
    {{- include "keyway.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "keyway.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
    - name: metrics
      port: 9090
      targetPort: metrics
