// Sealing payloads for keyway's own Store.
//
// This is the one backend where keyway holds a value at all, so it is the one
// place a mistake here loses secrets rather than merely metadata. AES-256-GCM,
// a fresh random nonce per version, and the key id recorded beside the
// ciphertext so a rotated deployment can still open what it wrote last year.
//
// The format is the Rust implementation's, byte for byte: a 12-byte nonce, a
// ciphertext with the 16-byte tag appended, the aad bound into the tag. A row
// the Rust server sealed opens here and vice versa — crypto_test.go pins that
// with a golden vector generated by the Rust crate.

package entity

import (
	"crypto/aes"
	"crypto/cipher"
	"crypto/rand"
	"encoding/base64"
	"errors"
	"fmt"
	"sort"
	"strings"
)

// nonceLen is AES-256-GCM's nonce: 96 bits.
const nonceLen = 12

// Sealed is a sealed payload, as a row stores it.
type Sealed struct {
	// KeyID is which key sealed this. Recorded per version rather than per
	// Store, so rotating the active key does not make yesterday's versions
	// unreadable.
	KeyID      string
	Nonce      []byte
	Ciphertext []byte
}

// UnknownKeyError is a key id that is not configured; a version sealed with
// it cannot be opened.
type UnknownKeyError struct {
	KeyID string
}

func (e *UnknownKeyError) Error() string {
	return fmt.Sprintf("key %q is not configured; a version sealed with it cannot be opened", e.KeyID)
}

// BadKeyError is a key that is not 32 bytes of base64.
type BadKeyError struct {
	KeyID  string
	Reason string
}

func (e *BadKeyError) Error() string {
	return fmt.Sprintf("key %q is not 32 bytes of base64: %s", e.KeyID, e.Reason)
}

// ErrUnopenable deliberately says nothing about why. A caller distinguishing
// "wrong key" from "tampered" learns something from a failure, and there is
// nothing useful they could do with it.
var ErrUnopenable = errors.New("the payload could not be opened")

// Keyring is the keys a Store can open payloads with, and the one it seals
// new ones under.
//
// More than one because rotation is not an instant: the active key seals
// everything new, and the retired ones stay configured for exactly as long as
// a version sealed under them still exists.
//
// A Keyring is immutable after construction and safe for concurrent use. Only
// the derived ciphers are held, never the raw material — the closest Go gets
// to Rust's Zeroizing, since nothing here can hand the bytes back out.
type Keyring struct {
	active  string
	ciphers map[string]cipher.AEAD
}

// String names the ids and nothing else, for the same reason the Rust Debug
// impl was written by hand: a default rendering would put key material in the
// first panic message or log line that touched a Keyring.
func (k *Keyring) String() string {
	ids := make([]string, 0, len(k.ciphers))
	for id := range k.ciphers {
		ids = append(ids, id)
	}
	sort.Strings(ids)
	return fmt.Sprintf("Keyring{active: %q, key_ids: [%s]}", k.active, strings.Join(ids, ", "))
}

// GoString redacts %#v the way String redacts %v.
func (k *Keyring) GoString() string { return k.String() }

// NewKeyring builds a keyring from base64 keys.
//
// It fails when a key is not 32 bytes of base64, or the active id names a key
// that was not given.
func NewKeyring(active string, keys map[string]string) (*Keyring, error) {
	ciphers := make(map[string]cipher.AEAD, len(keys))
	for id, material := range keys {
		aead, err := decodeKey(id, material)
		if err != nil {
			return nil, err
		}
		ciphers[id] = aead
	}
	if _, ok := ciphers[active]; !ok {
		return nil, &UnknownKeyError{KeyID: active}
	}
	return &Keyring{active: active, ciphers: ciphers}, nil
}

// ActiveID is the id new payloads are sealed under.
func (k *Keyring) ActiveID() string { return k.active }

// Seal seals a payload under the active key.
//
// `aad` is bound into the tag — pass the secret's identity, so a ciphertext
// lifted from one row into another fails to open rather than silently
// revealing the wrong secret's value.
func (k *Keyring) Seal(plaintext, aad []byte) (Sealed, error) {
	aead, ok := k.ciphers[k.active]
	if !ok {
		return Sealed{}, &UnknownKeyError{KeyID: k.active}
	}

	nonce := make([]byte, nonceLen)
	if _, err := rand.Read(nonce); err != nil {
		return Sealed{}, fmt.Errorf("generating a nonce: %w", err)
	}

	return Sealed{
		KeyID:      k.active,
		Nonce:      nonce,
		Ciphertext: aead.Seal(nil, nonce, plaintext, aad),
	}, nil
}

// Open opens a sealed payload with whichever key sealed it.
//
// It fails when the recorded key is not configured, or the payload does not
// authenticate.
func (k *Keyring) Open(sealed Sealed, aad []byte) ([]byte, error) {
	aead, ok := k.ciphers[sealed.KeyID]
	if !ok {
		return nil, &UnknownKeyError{KeyID: sealed.KeyID}
	}
	if len(sealed.Nonce) != nonceLen {
		return nil, ErrUnopenable
	}
	plaintext, err := aead.Open(nil, sealed.Nonce, sealed.Ciphertext, aad)
	if err != nil {
		return nil, ErrUnopenable
	}
	return plaintext, nil
}

func decodeKey(id, material string) (cipher.AEAD, error) {
	raw, err := base64.StdEncoding.DecodeString(strings.TrimSpace(material))
	if err != nil {
		return nil, &BadKeyError{KeyID: id, Reason: err.Error()}
	}
	if len(raw) != 32 {
		return nil, &BadKeyError{KeyID: id, Reason: fmt.Sprintf("decoded to %d bytes, not 32", len(raw))}
	}
	block, err := aes.NewCipher(raw)
	if err != nil {
		return nil, &BadKeyError{KeyID: id, Reason: err.Error()}
	}
	aead, err := cipher.NewGCM(block)
	if err != nil {
		return nil, &BadKeyError{KeyID: id, Reason: err.Error()}
	}
	return aead, nil
}

// AAD is the bytes a secret's identity contributes to the tag.
func AAD(store, name, version string) []byte {
	return []byte(store + "/" + name + "@" + version)
}
